# Generated by Django 4.0.4 on 2022-06-16 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_remove_orderproduct_variation_orderproduct_variation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='product',
            new_name='Product',
        ),
    ]
