# Generated by Django 4.0.4 on 2022-06-16 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_rename_product_orderproduct_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='Product',
            new_name='product',
        ),
    ]
