# Generated by Django 4.0.4 on 2022-06-16 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_rename_product_orderproduct_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='variation',
            field=models.ManyToManyField(blank=True, null=True, to='store.variation'),
        ),
    ]
