# Generated by Django 4.0.4 on 2022-06-16 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_alter_orderproduct_variation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='color',
        ),
    ]
