# Generated by Django 4.0.4 on 2022-06-23 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_order_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='disc_pice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
