# Generated by Django 4.0.4 on 2022-06-24 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Accepted', 'Accepted'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Confirmed', 'Confirmed'), ('Failed', 'Failed'), ('Delivered', 'Delivered')], default='New', max_length=10),
        ),
    ]
